.pre-commit-config.yaml
This adds [autoflake](https://github.com/myint/autoflake), an autofixer for unused imports and variables, to the pre-commit config.
=> pre-commit: Add autoflake

robot.py, utilities/git.py
This is mostly a copy-paste from last year, with the following changes:
- Use `git branch --show-current` to get the current branch name, and support detached HEAD.
- Avoid writing the file if it hasn't changed.
=> Log git commit info on robot init

Pipfile, Pipfile.lock, README.md
This adds a `Pipfile` for installing our requirements using [`pipenv`], to make creating a virtual environment simple.
Notably, VS Code has builtin support for `pipenv`.
Imported using `pipenv install -r requirements-sim.txt`.
[`pipenv`]: https://pipenv.pypa.io/en/latest/
=> Add pipenv support

.pre-commit-config.yaml
https://github.com/thedropbears/vision-2022/pull/11 showed that the `autoflake` pre-commit hook needs to be run with `--in-place`, as this is not a default.
=> pre-commit: Run autoflake with --in-place

utilities/scalers.py
This parameter is unused and untested.
This was removed in last year's robot code, as an obviously correct test was written and the code was shown to fail: https://github.com/thedropbears/pyinfiniterecharge/pull/141
=> scalers: scale_value: Remove exponent parameter

components/shooter.py
This offloads the feedforward voltage compensation to the motor controllers. A major benefit of this approach is that the voltage compensation will react closer to real time.
=> shooter: Use onboard voltage compensation

Pipfile, Pipfile.lock, requirements-sim.txt, requirements.txt
Requires roboRIO v4 image, and new image requires these updates.
=> Bump dependencies for roboRIO v4 image

robot.py
This puts our startup message before any hardware initialisation, so that we know when our robot code has begun starting when looking in the console.
=> robot: Log startup message at start of init

Pipfile, Pipfile.lock, requirements.txt
Fixes the `Out of memory` error on Linux when calling `repr` on a `TrapezoidProfile.State`, such as when RobotPy prints the locals when an exception occurs.
https://github.com/robotpy/robotpy-wpimath/commit/4b528a194d7b568fcb36220013a1f8a6202bdc5d
=> Bump wpimath to 2022.3.1.1

.vscode/launch.json, .vscode/tasks.json
Allow for running the simulator and deploying to the robot with single keyboard shortcuts.
This is largely copypasta from last year, with the following changes:
- Add configs to run pytest directly (will be removed when pyfrc tests are re-enabled)
- Make `deploy` the default build task
- Update tasks command for compatibility with newer Python VSCode extension
=> Add VSCode launch and tasks configs

controllers/shooter.py, robot.py
- The driver should be able to continuously ask the controller to fire until it fires
- Avoid the possible case of immediately attempting to take a second shot after we have fired, despite nobody currently commanding it to
=> Fix 'wants to fire' flag resetting

components/chassis.py, components/shooter.py
We're still saturating the CAN bus apparently.
See #37
=> Reduce CAN status rates on shooter and steer encoders

components/turret.py
We attempt to resynchronise the turret encoder every time the robot is disabled or enabled. However, we were previously throwing away any rollover from the absolute encoder every time we did this.
This preserves any rollover from the absolute encoder tracked by the roboRIO, whilst still ensuring it is still within the physically possible angles of the turret.
=> turret: Fix throwing away angle wraparound

components/chassis.py
The field oriented drive code assumed that the IMU matches our coordinate system. However, this is not true as our starting poses do not face forwards.
This fixes all usages of the IMU yaw to instead read the rotation from the estimated pose, which accounts for the offset between the robot heading in the coordinate system and the yaw from the IMU.
=> Fix usage of IMU yaw

components/indexer.py, controllers/indexer.py
This moves the colour and alliance checking logic into methods on the `CargoColour` enum, changing the `Indexer` component to read only once from the colour sensor in its `execute` method.
The enum has been hoisted to the module level, as it is not an intrinsic property of the indexer.
=> indexer: Simplify colour matching 🌱

components/shooter.py
- Make the shooter flywheels forget their commanded speed when disabling the robot
- Avoid running the PID controller to 0 velocity
=> shooter: Naturally stop motors when not commanded

controllers/leds.py, robot.py
The request to pulse from `teleopPeriodic` was being overwritten by the `LedController`.
=> Fix LEDs not pulsing on auto shoot

components/leds.py
Previously the roboRIO synchronising its system time with the Driver Station could disrupt the flash pattern. This fixes that by using a monotonic clock, avoiding a clock that can suddenly go forwards or backwards in time.
=> leds: Use monotonic clock instead of system clock

components/chassis.py, robot.py
We will use the builtin offset functionality on the CANCoders: https://docs.ctre-phoenix.com/en/stable/ch12a_BringUpCANCoder.html#choose-absolute-sensor-offset
**Do not merge before the CANCoders are installed and configured.**
=> Use CANCoders for swerve absolute rotation encoder

components/chassis.py
**Problem**: The `SwerveModule.set` method attempted to account for the wraparound of the module by getting the current angle of the module and calculating the delta between the commanded angle and current angle. However, this was always reading from the absolute encoder rather than the motor sensor.
Since swapping out our heavyweight solution with the CANCoders, I believe the absolute encoder has been giving readings within [0,τ], due to specifically reading the absolute angle. This wouldn't have been the case with the previous solution.
**Solution**: This renames the get angle methods to be explicit about the _type_ of angle it's reading, fixes the code to only ever read the absolute encoder when synchronising the encoders, and cleans up the constants for clarity.
#124 has been reverted …
=> Fix swerve angle calculations and clean up

.gitignore, Pipfile, Pipfile.lock, controllers/indexer.py, controllers/shooter.py, requirements.txt, robot.py
Docs:
- https://docs.wpilib.org/en/stable/docs/software/telemetry/datalog.html
- https://robotpy.readthedocs.io/projects/wpilib/en/stable/wpilib/DataLogManager.html#wpilib.DataLogManager
DataLogTool is part of the WPILib 2022.4.1 installer, or available from https://frcmaven.wpi.edu/artifactory/wpilib-mvn-release-local/edu/wpi/first/tools/DataLogTool/
`wpilib` package update is required due to broken bindings in earlier versions of RobotPy.
=> Use wpilib.DataLogManager for detailed logging

autonomous/autonomous.py, components/chassis.py, components/vision.py, robot.py, simgui.json
Needs some twiddling of waypoint heading to get it fully smooth.
Sets the desired chassis heading directly in the call to `drive_controller.calculate()` because the PID controller for yaw is profiled, therefore it does the ramping up and down for us.
=> Use WPIMath trajectory generators for auto

robot.py
We're sometimes getting MemoryErrors when deploying after the robot code has run for a while.
Run the camera stream in process to reduce RAM usage by about 8 MB.
=> robot: Run camera stream in robot process

physics.py, robot.py
This only takes into account the inertia of the VersaWheels (i.e. none of the pulleys, gears, or hex shaft), calculated from the CAD. Far from perfect, but should be enough to exercise the state machines.
=> Add simple shooter flywheel sim

autonomous/autonomous.py
Now you dont have to change the pose twice if you want to move a waypoint
Also removed four ball as if our alliance partner can't do a five ball we will.
=> Use last movements end as start for next

controllers/shooter.py
Ref: https://github.com/thedropbears/pyrapidreact/issues/178#issuecomment-1094168715
Reviewing this PR with "hide whitespace changes" turned on is recommended.
=> shooter: Fix divide by zero in leading shots

controllers/leds.py
Before a match, the robot will never be in range to shoot. Hence, if vision was not connected, the "not in range" status would previously always overwrite the "vision disconnected" status.
=> leds: Fix vision status

components/chassis.py, components/indexer.py, components/shooter.py
The earlier we reduce CAN bus traffic, the more likely subsequent sends on the CAN bus will succeed.
=> Reduce CAN status frames before configuration
