- requirements.txt
https://www.chiefdelphi.com/t/robotpy-ctre-2022-is-currently-broken/400891/3?u=auscompgeek
> Update robotpy-ctre to avoid segfaults

- Pipfile
- Pipfile.lock
- requirements-sim.txt
- requirements.txt
- pyfrc for passing robot instance to physics
- robotpy-wpilib-utilities for test mode fix
> Update RobotPy dependencies

- utilities/ctre.py
This adds a facade around the Talon sensor API which mimics the Spark Max encoder API.
> Add TalonEncoder

- components/indexer.py
- robot.py
> removed indexer feeder motor

- requirements-test.txt
- tests/test_trajectory.py
- utilities/trajectory_generator.py
Utilities for auto to sample from a linear path, a smoothed linear path and do pose2d lerp
PR stack:
- #24 :point_left: this PR
- #25
> Added path smoothing utils

- robot.py
Per https://pdocs.kauailabs.com/navx-mxp/guidance/selecting-an-interface/
> robot: Use SPI for navX

- components/chassis.py
- components/shooter.py
- robot.py
updated swerve to use absolute mag encoders on separate dedicated motor controllers
> Absolute swerve

- .flake8
- Make sure editor linter integrations show the warnings configured in pre-commit
- Ignore rules that conflict with black
> Add flake8 config

- components/chassis.py
stops swerve snapping in rotation once a zero command is received.
I just tested this on the bot and it works fine
> added check to stop swerve modules from snapping on command

- autonomous/autonomous.py
- components/chassis.py
- robot.py
- utilities/trajectory_generator.py
Follows a linear path between waypoints with a trapazoidal velocity profile.
It will follow a trapazoidal velocity profile to stop before the next waypoint if it is holding a ball otherwise will not stop
PR stack:
- #24
- #25 :point_left: this PR
> Auto driver

- components/chassis.py
> chassis: Use onboard voltage comp for drive

- components/shooter.py
- controllers/shooter.py
note that these ranges where calculated for index speed of 0.8 by mistake
> Range interpolation

- components/shooter.py
This pr is solely to find the optimal control loop gains for the shooter that decrease steady state error for reliable shots
> shooter tuning

- autonomous/autonomous.py
- components/intake.py
- components/shooter.py
- components/turret.py
- controllers/indexer.py
- controllers/shooter.py
- robot.py
shooter controller recives wants_to_fire from robot.py or auto, when its flywheels are at speed and its aiming at the target it sets wants_to_fire on indexer which will feed the ball if we have one
> Shooter control

- components/shooter.py
This cleans up the unused and irrelevant constants in the shooter.
> shooter: Clean up constants

- autonomous/autonomous.py
> autonomous: Pass waypoints as constructor param

- autonomous/autonomous.py
- components/chassis.py
- components/shooter.py
- components/turret.py
- controllers/shooter.py
still have to create flight time lookup tablee
> Leads shots

- tests/test_scalers.py
- Test all the boundary conditions
- Check the result is always between 0 and the given value for deadzone and exponential
- Test that deadzone and exponential are odd functions
> test_scalers: Add more assertions

- components/turret.py
I meant to move this in #65 :facepalm:
> turret: Remove redundant target angle constrain

- components/chassis.py
- robot.py
> added reset heading button

- autonomous/autonomous.py
Four ball auto starting on left side going to the terminal and two ball starting on left side
> more auto routines

- autonomous/autonomous.py
> fix pose to Waypoint

- components/indexer.py
- controllers/indexer.py
allow colour sensor enum to keep rolling tally of colour values when it sees a ball to increase its confidence over longer periods
> colour sensor consistency

- robot.py
is there anything else we need to run in test mode?
> Added test mode

- components/shooter.py
- controllers/shooter.py
dosent run shooter until we have a ball or are intaking
> Dont run shooter immediately

- autonomous/autonomous.py
- components/chassis.py
- components/shooter.py
- components/turret.py
- components/vision.py
- controllers/indexer.py
- controllers/shooter.py
- robot.py
to prevent any more total spanner moments.
> Type hint everything and fix docs

- components/turret.py
- controllers/shooter.py
* Create separate +ve/-ve rotation limits
* Correctly allow for turret overlap
> Turret limits

- components/indexer.py
Docs: https://docs.revrobotics.com/sparkmax/operating-modes/control-interfaces#periodic-status-frames
> indexer: Lower periodic status frame rates

- components/leds.py
- controllers/leds.py
- controllers/shooter.py
- robot.py
LED component will now take input through 3 functions (pulse, flash,
solid) which if not provided with colour will continue to use the
current led colour. The values of the leds when using these modes (pulse
brightness, toggle leds in flash) are called in execute.
> Updated LED functions

- components/chassis.py
- controllers/shooter.py
- robot.py
sets the robot pose to the safe spot while the codriver x button is pressed
> estimator failsafe

- robot.py
Reference: https://github.com/kauailabs/navxmxp/blob/5e010ba810bb7f7eaab597e0b708e34f159984db/roborio/java/VSCodeExamples/navXMXP_ExpansionIO/src/main/java/frc/robot/Robot.java#L208
> Move turret absolute encoder to navX MXP pin 0

- components/chassis.py
- components/vision.py
- robot.py
this will trust vision twice as much during teleop
> trusts vision more during teleop

- components/turret.py
- controllers/shooter.py
- robot.py
- stricter requirements to shoot in auto shoot mode 
- acceleration limit in both modes
- turret allowed error based on distance
> Stricter shoot tests in auto shoot mode

- components/chassis.py
reversed the required drive motors
> Fix driving motor directions

- Pipfile
- Pipfile.lock
- requirements.txt
```sh
robotpy-installer download -r requirements.txt
robotpy-installer install -r requirements.txt
> Bump robotpy-wpiutil to 2022.4.1.1 for DataLog

- components/chassis.py
- controllers/leds.py
- robot.py
increased turn speed
desatture swerve speeds
remove the vision led indicators and make them not pulse, if vision is down not much can be done during the match
> Driving tweaks

- components/indexer.py
- simgui.json
... so that our logs aren't too messy.
> indexer: Group objects in LiveWindow

- robot.py
Trying to isolate what looks like a deadlock on destruction in #151.
> robot: Enable swerve and turret motors in sim

- components/shooter.py
https://docs.ctre-phoenix.com/en/stable/ch14_MCSensor.html#velocity-measurement-filter
> shooter: Reduce velocity measurement filter

- components/indexer.py
lowered the colour threshold to 400 and the minimum readings to 2, we may also want to make balls not read treated as our balls (since that's most of what we pick up)
> Colour tuning

- components/turret.py
... so our angle we read is slightly more precise.
> turret: Add RADIANS_PER_COUNT constant

- components/vision.py
- controllers/leds.py
fixed the check for if the vision is connected
> Fixed vision is connected check

- controllers/indexer.py
- controllers/shooter.py
Reject opposition cargo through turret if possible.
Note that this does not address the auto-retraction issues raised in the discussion of #157
> Turret rejection

- robot.py
adds controls from codriver to joystick so max can focus on looking at balls (his favourite passtime)
> added controls to joystick

- components/chassis.py
- components/shooter.py
- components/vision.py
- controllers/shooter.py
Lead shots with only the odometry so we can set the vision trust higher without it making the leading shots noisy
> Lead shots from odom only

- components/leds.py
- controllers/leds.py
- robot.py
reworks the led component and adds a pacman and rainbow led pattern for disabled.
Also changed the colours used in teleop to display how many balls we have
> Led patterns

- components/chassis.py
- components/vision.py
- controllers/leds.py
- controllers/shooter.py
- robot.py
I would like to try out these controls
controls are:
left stick: translation
right stick x: rotation
right bumper: intake down, hold to hold down
left bumper: raise intake
left trigger: lower movement speed
right trigger: fire
> Added xbox controls for driving

- components/chassis.py
- components/indexer.py
- components/intake.py
- components/shooter.py
- components/turret.py
- components/vision.py
- controllers/indexer.py
- controllers/leds.py
- controllers/shooter.py
- robot.py
changes from macquarie days 1 and 2, also found afterwards that the vision std dev changes we made werent having any effect as it was getting overwritten in teleopinit
> Macquarie 1
